apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "Prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.observability.svc:8080",
                "version": 1
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "Loki",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki.observability.svc:3100",
                "version": 1
            }
        ]
    }