---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: observability
data:
  grafana.ini: |
    [server]
      protocol = http
      http_port = 3000
      # cert_file = /etc/grafana/certs/tls.crt
      # cert_key  = /etc/grafana/certs/tls.key
      root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
      serve_from_sub_path = true
    [analytics]
      reporting_enabled = false
      check_for_updates = true
    [log]
      mode = console
      level = info
    [paths]
      data         = /var/lib/grafana/data
      logs         = /var/log/grafana
      plugins      = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning