apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-promtail-app
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/ozgureroglu/Kubernetes-Observability/main/Loki-Promtail/helm/loki-stack-values.yaml
    chart: grafana/loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.10
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true